name: mapbox_gl_platform_interface
description: A common platform interface for the mapbox_gl plugin.
version: 0.14.0
homepage: https://github.com/tobrun/flutter-mapbox-gl

dependencies:
  flutter:
    sdk: flutter

  mapbox_gl_platform_interface:
    git:
      url: https://github.com/MobileSoftHK/maps.git
      path: mapbox_gl_platform_interface
      ref: dogtrace/release-0.14.0

  mapbox_gl_web:
    git:
      url: https://github.com/MobileSoftHK/maps.git
      path: mapbox_gl_web
      ref: dogtrace/release-0.14.0

  meta: ^1.0.5

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
